### ISSUE TITLE
Headings structure

### ISSUE THREAD

**Issue by vinitra** [EPIC-guide/epic-guide.github.io#45]
We can discuss this, but I think it's nicer to move back to the "Year 1" for the "getting started" page! I'm also not sure "resources and responsibilities" is quite the right heading for the third tab... Maybe just calling it "Year 2+" or "PhD Life"?

**Comment by vinitra** [comment]
Also maybe keeping Resources (compute + storage, IC people website, EPFL infra) separate from the stuff directly about PhD responsibilities?

**Comment by SolalPirelli** [comment]
Closed by the restructuring
