### ISSUE TITLE
Graduation Timeline

### ISSUE THREAD

**Issue by vinitra** [EPIC-guide/epic-guide.github.io#48]
There was something mentioned about not graduating in September because it makes you ineligible for certain awards in the right year -- that could be mentioned here (https://epic-guide.github.io/last/timeline).

**Comment by shardulc** [comment]
Solal, Feb 2024: "How does one announce to EPFL a public defense? Do I have to wait til my advisor has approved the final version of the thesis or some other point?"

:eyes:
