### ISSUE TITLE
Add info/links on exchanging the driver's license, maybe personal experiences for certain countries

### ISSUE THREAD

**Issue by vsanca** [EPIC-guide/epic-guide.github.io#7]
https://www.expatica.com/ch/living/transportation/exchanging-a-foreign-drivers-licence-in-switzerland-102892/

**Comment by SolalPirelli** [comment]
@vsanca this is the only issue still open, want to submit a PR? 😄

**Comment by shardulc** [comment]
I can get this started for converting US licenses since I did that a few months ago. (Feel free to ping me if I haven't done anything in a month)

**Comment by SolalPirelli** [comment]
poke @shardulc :p
